### PR TITLE
BZ-1283109 - REST API roles restrictions do not work on WebSphere and…

### PR DESCRIPTION
**Pull request by mswiderski**
… WebLogic

master cherry pick of https://github.com/droolsjbpm/kie-wb-distributions/pull/151

### CODE REVIEW

**Comment by mswiderski** [comment]
anyone would like to review?

**Comment by manstis** [comment]
+1 to merge (based on Marco's comments on the original PR - that wasn't merged anyway?!?)... it's possibly the blind leading the blind...

**Comment by mswiderski** [comment]
thanks @manstis, PR for 6.3.x was closed as currently it should not be merged and once there will be decision to merge it in I'll reopen it just to avoid having PRs that gets outdated and still being open

**Comment by csadilek** [comment]
master: e42d4733c67c3e1af7cdd8f04794a3272d94dffe

**Pull request closed without merging**
