### PR TITLE
Fixes after IP BOM 7.0.0.CR4 upgrade

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
All PRs in this IP BOM 7.0.0.CR4 series need to be merge together:
https://github.com/errai/errai/pull/180
https://github.com/uberfire/uberfire/pull/400
https://github.com/dashbuilder/dashbuilder/pull/187
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/222
https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/148
https://github.com/droolsjbpm/drools/pull/813
https://github.com/droolsjbpm/optaplanner/pull/198
https://github.com/droolsjbpm/jbpm/pull/486
https://github.com/droolsjbpm/droolsjbpm-integration/pull/498
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/28
https://github.com/droolsjbpm/guvnor/pull/325
https://github.com/droolsjbpm/kie-wb-common/pull/389
https://github.com/droolsjbpm/drools-wb/pull/205
https://github.com/droolsjbpm/jbpm-form-modeler/pull/55
https://github.com/droolsjbpm/jbpm-designer/pull/299
https://github.com/droolsjbpm/jbpm-console-ng/pull/431
https://github.com/droolsjbpm/kie-wb-distributions/pull/301

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by psiroky** [comment]
I believe the test failures are caused by/related to the recent UF security commits. Should be fixed when PR https://github.com/droolsjbpm/guvnor/pull/326 gets merged.

**Comment by livthomas** [comment]
I can confirm that the test failures are caused by [GUVNOR-2565](https://issues.jboss.org/browse/GUVNOR-2565) and not by the changes in this pull request.

**Comment by csadilek** [comment]
+1

**Pull request merged**
