### PR TITLE
6.4.x Branch selector fix

### PR DESCRIPTION
**Pull request by Rikkola**
Bug 1313094 - If one user changes a branch, the branch is changed for all the users
    Bug 1313095 - Repository listing and File explorer in Adminstration perspective were often out of sync

(cherry picked from commit b948e1469ff371a12a55c4cf98237e6b3414fc39)

https://github.com/droolsjbpm/guvnor/pull/271
https://github.com/droolsjbpm/kie-wb-common/pull/284
https://github.com/droolsjbpm/drools-wb/pull/136
https://github.com/droolsjbpm/jbpm-console-ng/pull/350
https://github.com/droolsjbpm/jbpm-designer/pull/171
https://github.com/droolsjbpm/jbpm-form-modeler/pull/41
https://github.com/droolsjbpm/optaplanner-wb/pull/41
https://github.com/droolsjbpm/kie-wb-distributions/pull/217

### CODE REVIEW

**Comment by csadilek** [comment]
6.4.x: c93069bbfe703b1b140fdd83c40810d77ded97c0

**Comment by csadilek** [comment]
@Rikkola thanks, all done now. @manstis @psiroky for completeness I would like to point out that this was 1 fix, but *24* PRs (8 repos, 3 branches). All is not well. ;)

**Comment by psiroky** [comment]
@csadilek oh man, I share your pain! Being gatekeeper for those 10 days really opened my yes. We need to come up with improvements asap. This is not bearable.

**Comment by manstis** [comment]
To be fair Toni took this bug fix as an opportunity to refactor something related - which happened to hit every repository... and as for branches... well not much we ca  do about that (if a bug fix is needed for a production roll up patch and comes during a release cycle)

**Comment by csadilek** [comment]
@manstis sure nobody is saying @Rikkola did anything wrong, in fact he must have felt the pain the most ;). But 24 PRs for this is a fact and I don't think that's good.

**Comment by Rikkola** [comment]
Yep, spend a good amount of this week just compiling. Since it took some time to get 6.3.x and 6.4.x branches done and verified. Even when the change to each webapp was quite small.

One thing we can do is reduce the redundancy in each webapp. Probably would not have helped here, but would in other cases where I have had to touch each one of them.

And I could have left the refactoring related to repository creation out. If it was done separately it would have still touched each webapp in master and 6.4.x. I used the refactoring to kill the HashMap we had for settings and make sure I managed to remove all the locations where we stored the current branch using the map.

**Comment by Rikkola** [comment]
Maybe the jbpm repositories could be merged. We have over 10 editors in drools-wb and feels like the jpbm editors have 1-2 each. I don't think we publish separate wars for them anymore.

**Comment by mdproctor** [comment]
I think we have baby steps on how to proceed on reducing the number of repo's. And we can work at this iteratively, to reduce stuff - especially for 7.0. I think we have a general consensus on that from all parties - incremental baby steps, that is.

**Pull request closed without merging**
