### PR TITLE
JBPM-5071 : remove of jbpm runtime from workbench

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/JBPM-5071

@mswiderski I think I got them all.

### CODE REVIEW

**Comment by mswiderski** [comment]
+1 to merge

**Comment by psiroky** [comment]
Sorry for hijacking this PR, but should we still support Tomcat 7? I believe we should just move to Tomcat 8+. WDYT?

**Comment by mswiderski** [comment]
Makes sense to move to tomcat 8, there should not be much of a debate deference but these changes are needed any way

**Comment by psiroky** [comment]
Yeah, I am mainly asking because of the WAR name. We should change that to `tomcat8`.

**Comment by psiroky** [comment]
I've found one possible leftover: `kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/classes/META-INF/persistence.xml`. Do we still need the persistence config?

**Comment by mswiderski** [comment]
No, we don't need it anymore

**Comment by Rikkola** [comment]
I'll add it to this PR.

**Comment by Rikkola** [comment]
Updated and also removed the file kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/classes/META-INF/persistence.xml

**Comment by manstis** [comment]
https://github.com/droolsjbpm/kie-wb-distributions/pull/423 has been merged. You may want to synchronise your fork and rebuild this PR...

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
