### PR TITLE
Jbpm-5397: Stunner - add kie-wb-common-stunner-bpmn-project-api module

### PR DESCRIPTION
**Pull request by jlindop**

### CODE REVIEW

**Comment by jlindop** [comment]
Needs these other PR's:
https://github.com/droolsjbpm/kie-wb-common/pull/579
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/320

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by romartin** [comment]
Local compilation and the webapps are working. Let's wait for juenkins, +1

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by manstis** [comment]
https://github.com/droolsjbpm/kie-wb-distributions/pull/423 has been merged. You may want to synchronise your fork and rebuild this PR...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jlindop** [comment]
jenkins please retest this

**Comment by jlindop** [comment]
@manstis  Hi Michael. Will you merge this and the related PR's
droolsjbpm/kie-wb-common#579
droolsjbpm/droolsjbpm-build-bootstrap#320

I rebased them all this morning and they're building ok. Thanks to @paulovmr, @psiroky and @manstis for fixing the test errors last week!

**Pull request merged**
