### PR TITLE
BZ-1002303 Enable users to apply the locale of their choice for all UI's...

### PR DESCRIPTION
**Pull request by bxf12315**
... that have been localized

### CODE REVIEW

**Comment by manstis** [comment]
We will also need this for kie-drools-wb. Could you please modify your pull
request? I'll review both PRs fully later. Thank-you.

Sent on the move

**Comment by bxf12315** [comment]
ok,  i will add the feature into kie-drools-web

**Comment by bxf12315** [comment]
BTW: if you build kie-web-webapp, you need remove this line(https://github.com/droolsjbpm/kie-wb-distributions/blob/master/kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/FastCompiledKIEWebapp.gwt.xml#L7) .

**Comment by Salaboy** [comment]
merged in master

**Pull request closed without merging**
