### PR TITLE
BZ1263753 - Update task perspective

### PR DESCRIPTION
**Pull request by cristianonicolai**
New perspective does not allow new tasks to be created

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/droolsjbpm/jbpm-console-ng/pull/390

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@cristianonicolai Hi.. can you confirm the failing tests are not as a result of the changes to the "loading" popup? The errors state Selenium was unable to find an element "carousel-caption" and a quick search of what I believe to the applicable HTML page doesn't reveal the element either.

**Comment by cristianonicolai** [comment]
@manstis looks like the selenium test is expecting one of the splash screens to be loaded: https://github.com/droolsjbpm/kie-wb-distributions/search?p=1&q=carousel-caption

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
@jhrcek @psiroky Hi, I know the Selenium tests can be problematic but neither @cristianonicolai nor myself are sure what's causing the failures. @jhrcek Would you mind taking a look please (6.4.x doesn't suffer any problems; and AFAIK master should be identical to 6.4.x with regard to the "carousel-caption" CSS selector failing in the tests).

**Comment by jhrcek** [comment]
@cristianonicolai @manstis 
Let me explain:
Waiting for "carousel-caption" is my implementation of waiting for kie-wb to load after login.
The selenium smokes fail with the mentioned exception when - after login - there is that "Loading application" popup displayed indefinitely as you can [see in the screenshot](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-distributions-pullrequests/177/artifact/kie-wb-smoke-tests/kie-wb-smoke-tests-main/target/screenshots/LoginIntegrationTest_loginAndLogout.png)

We've been facing this issue for some time now and still don't know what is the exact cause.
Summary of what we know do far:
- it happens in CentralCI jenkins environment (only rarely on our middleware jenkins)
- it usually only happens in the first selenium test (the first time the app is loaded after login)
- with @psiroky we tried increasing the timeout to rule our suspicion that it's just caused by slow machines [see this PR](https://github.com/droolsjbpm/kie-wb-distributions/pull/225)
 however even increasing the timeout to 2 minutes (-Dselenium.homepage.loading.timeout=120) didn't help and the tests were still failing with the same timeout
- My colleague @mwinkler was trying the [workaround](https://github.com/droolsjbpm/kie-docs/commit/5b54cd0a72f4d7e248f571bcb6fb156e9c4f50da) documented by Michael in our central CI jenkins environment, but to no effect - the tests were still occasionally failing with the same exception.

We're slowly running out of ideas about things to try to debug this issue :)

**Pull request merged**
