### PR TITLE
Upgrade Tomcat 7 assembly to use Servlet 3

### PR DESCRIPTION
**Pull request by csadilek**
- Simple change to web.xml to upgrade to Servlet 3. This is in line with all other assemblies.

### CODE REVIEW

**Comment by psiroky** [comment]
+1

**Comment by csadilek** [comment]
Thanks @psiroky.

**Comment by manstis** [comment]
I assume, oh master of merge, that it's OK to merge your own PRs if +1'ed
from a colleague? ;-)

**Comment by csadilek** [comment]
@manstis I think that's what we agreed on last week, yes.

**Pull request merged**
