### PR TITLE
JBPM-4900 - Enhance TaskList Search capability

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/droolsjbpm/jbpm-console-ng/pull/275

### CODE REVIEW

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: 5d09141465c75bdb7ba788d5968ef3a6c307038a

**Comment by csadilek** [comment]
reverted: 977780c4e8916b84fefcd995ab027d1067bba244

**Comment by mswiderski** [comment]
ok, this one is now ready to be merged

**Comment by csadilek** [comment]
master: 2fc33b6d9b806404528984bce7041abb55e85d0e

**Pull request closed without merging**
