### PR TITLE
BZ-1275796 - Fixed banner and navigation menu styling to match Patter…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…nFly guideline for the product

### CODE REVIEW

**Comment by manstis** [comment]
Where is banner.html used?

**Comment by cristianonicolai** [comment]
banner.html is used to override the same file from the community version. In this case the difference is the color scheme, using red and grey instead of blue and black.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks!

master: 803eb5e18d78e6f57911fd2cf237d976ae173b78

**Pull request closed without merging**
