### PR TITLE
JBPM-4625 Generation of JPA enabled models

### PR DESCRIPTION
**Pull request by wmedvede**
- Fix for avoiding the undesired collapse of the Tool Windows in certain scenarios, e.g: when selected field changes, etc.

### CODE REVIEW

**Comment by manstis** [comment]
Does this need Eders PR merged first?

**Comment by wmedvede** [comment]
Not necessary, Eders's PRs on uberfire and kie-wb-distributions are complementary. 
If Eder's PR can't be merged for the 6.3.0.Final, this PR will at least improve some scenarios for the docks.

**Comment by wmedvede** [comment]
I'll check this after Eders PR merge

**Comment by manstis** [comment]
This has merge conflicts after applying Eder's PR.. could you please rebase and correct?

**Pull request closed without merging**
