### PR TITLE
JBPM-4802 - Removed dropdown to access task list

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by csadilek** [comment]
This is a +1 but I will wait for other more familiar to take a look?

**Comment by manstis** [comment]
Neus or salaboy are potential candidates.

**Comment by cristianonicolai** [comment]
@Salaboy, please have a look when you got a chance.

**Comment by Rikkola** [comment]
I think Salaboy is travelling, so response time might be longer. He should be back next week.

**Comment by cristianonicolai** [comment]
@nmirasch Would you mind reviewing this PR, thanks :)

**Comment by csadilek** [comment]
hmm I +1ed this 24 days ago and no other feedback. So merging...

**Comment by csadilek** [comment]
master: b11646c30f39c3912c0e15101a06ac9874a964a7

**Pull request closed without merging**
