### PR TITLE
BPMSPL-252: [GSS-RFE] Ability to check duplicate of ReleaseId (GroupId, ArtifactId and Version) with existing projects

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/BPMSPL-252

### CODE REVIEW

**Comment by manstis** [comment]
Part of the following ensemble:

https://github.com/droolsjbpm/drools/pull/633
https://github.com/droolsjbpm/guvnor/pull/240
https://github.com/droolsjbpm/kie-wb-common/pull/236
https://github.com/droolsjbpm/drools-wb/pull/117
https://github.com/droolsjbpm/kie-wb-distributions/pull/187

**Comment by manstis** [comment]
@mrietveld Would you mind taking a look please?

**Comment by mrietveld** [comment]
+1 (when tests complete successfully? :) ) 

Good work, Michael.

**Comment by manstis** [comment]
@psiroky Build error is "java.lang.OutOfMemoryError: Java heap space" IDK if this needs a Jenkins tweak or the parameters passed in the Maven build configuration? Compiled OK locally.

**Comment by manstis** [comment]
*Documentation*
https://github.com/droolsjbpm/kie-docs/pull/40

**Comment by psiroky** [comment]
I've tweaked the Jenkins config, should be fixed now (will check the build result).

**Comment by csadilek** [comment]
master: b010cb5ef93bcd260bb14ad4e6d53c90d12c3130

**Pull request closed without merging**
