### PR TITLE
JBPM-5338: Remove kie-config-cli

### PR DESCRIPTION
**Pull request by jhrcek**
see https://issues.jboss.org/browse/JBPM-5338 for more details

### CODE REVIEW

**Comment by manstis** [comment]
+1 from me :-)

@mswiderski @porcelli @csadilek Any objections?

**Comment by mswiderski** [comment]
definitely +1 from me too

**Comment by psiroky** [comment]
+1 from me as well. Removing stuff we don't need anymore is always good :)

**Comment by manstis** [comment]
@jhrcek Could you also submit a PR for ```kie-docs``` about its removal with a summary of the reasoning from the JIRA?

**Comment by jhrcek** [comment]
@manstis: Sure, I'll create PR for `kie-docs` tomorrow.

**Comment by jhrcek** [comment]
PR for kie-docs created: https://github.com/droolsjbpm/kie-docs/pull/168

**Comment by csadilek** [comment]
+1

**Pull request merged**
