### PR TITLE
DO NOT MERGE - [6.3.x] BZ-1319053: Messages window can't be reopened after closing

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (thanks again...)

**Comment by manstis** [comment]
(Erm, I didn't see why there's 3 PRs... I guess master, 6.4.x and 6.3.x? - we should not be committing to 6.3.x at the moment - until the current roll patch is released)

**Comment by paulovmr** [comment]
@manstis Hi, I made a PR for 6.3.x too because the issue mentioned the 6.2.0 version. If this shouldn't be here I apologize, and feel free to close it without merge the commit.

**Comment by manstis** [comment]
@paulovmr, @Rikkola and I have been raising the PRs but commenting them clearly that they should not be merged.. the next rollup patch will be soon (AFAIK)

**Comment by paulovmr** [comment]
@manstis Ok, I've changed the PR's title now. Thanks!

**Comment by manstis** [comment]
@paulovmr Hi.. is this PR still required?

**Comment by paulovmr** [comment]
@manstis Hi, I am going to close it, since the ticket is already marked as verified and the target release was 6.3.0 (branch 6.4.x).

**Pull request closed without merging**
