### PR TITLE
6.3.x cache improvements

### PR DESCRIPTION
**Pull request by csadilek**
Cherry picked from master for (newly created) https://bugzilla.redhat.com/show_bug.cgi?id=1283304

**This carries 2 commits!**

Depends on: https://github.com/uberfire/uberfire-extensions/pull/125

### CODE REVIEW

**Comment by csadilek** [comment]
@mswiderski @manstis as discussed, we were asked to cherry-pick the cache improvements to 0.7.x/6.3.x.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
@porcelli please merge after confirmation. thanks.

**Comment by porcelli** [comment]
https://github.com/droolsjbpm/kie-wb-distributions/commit/3587e8b2441a918e7349e4a7627c3f8f8268d95c

**Pull request closed without merging**
