### PR TITLE
Add kiemgmt and kie-server roles to admin user

### PR DESCRIPTION
**Pull request by cristianonicolai**
Allow admin user to have access to Asset Management by default

### CODE REVIEW

**Comment by manstis** [comment]
Nice idea; could you please include kie-drools-wb too?

**Comment by manstis** [comment]
Actually, while you're at it, kie-server role would probably be good too :-)

**Comment by cristianonicolai** [comment]
@manstis done :)

**Comment by manstis** [comment]
Thanks, +1 to merge.

**Comment by csadilek** [comment]
6.4.x: ad80ef46dbf01e6dc2fc81fc875838fad7de9129

**Pull request closed without merging**
