### PR TITLE
UF-343: User without assigned role has all the permissions allowed

### PR DESCRIPTION
**Pull request by dgutierr**
Fix + tests

@manstis Can you verify please?

NOTE: This PR depends on uberfire/uberfire#439

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (when green).. Looks good!

**Comment by dgutierr** [comment]
@psiroky Any idea why the build is failing?

**Comment by psiroky** [comment]
@dgutierr Jenkins has troubles cloning from github.

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by csadilek** [comment]
jenkins retest this.

**Pull request merged**
