### PR TITLE
GUVNOR-2710 : Make client side Verifier a web worker.

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-2710

All the PRs:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/321
https://github.com/droolsjbpm/kie-wb-common/pull/581
https://github.com/droolsjbpm/drools-wb/pull/352
https://github.com/droolsjbpm/optaplanner-wb/pull/123
https://github.com/droolsjbpm/kie-wb-distributions/pull/421

### CODE REVIEW

**Comment by manstis** [comment]
@Rikkola Please check you're updated all ```web.xml``` [files](https://github.com/Rikkola/kie-wb-distributions/blob/5bc0339d6be880305b9a74b2421963d4f7103e60/kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml). There might be a similar one for kie-wb.

**Comment by Rikkola** [comment]
Updated the 2 Tomcat web.xml files, but still haven't managed to test the wars. Found several issues with the wars themself and today can't even compile kie-wb-distributions. Leaving it for now and fixing the notes in drools-wb PR.

**Comment by manstis** [comment]
@Rikkola please tell me when these are good to be re-reviewed!

**Comment by manstis** [comment]
https://github.com/droolsjbpm/kie-wb-distributions/pull/423 has been merged. You may want to synchronise your fork and rebuild this PR...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
Haven't been able to test Tomcat, but will do as soon as possible.

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request merged**
