### PR TITLE
RHBPMS-4430: Remove Russian and Chinese (Traditional) from language dropdown

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
Part of an ensemble:

* https://github.com/droolsjbpm/kie-wb-common/pull/533
* https://github.com/droolsjbpm/kie-wb-distributions/pull/388

**Comment by cristianonicolai** [comment]
@paulovmr @manstis I'm wondering if we should also remove the reference to these languages in the [zanata.xml](https://github.com/droolsjbpm/kie-wb-distributions/blob/master/src/main/config/zanata.xml) file across all repos.

**Comment by paulovmr** [comment]
Hi @cristianonicolai , I think we can. @mbiarnes @manstis wdyt? is there any unwanted impact in doing this?

**Comment by manstis** [comment]
@paulovmr I agree with @cristianonicolai the entries in the various ```zanata.xml``` files can go too (it's going to hit every workbench related repository; so you could always just co-ordinate it via BSIG - list repos, assign names and ask for it to be done!?!)

**Pull request merged**
