### PR TITLE
Bug 1316224 - User can not create projects in any other repository than master

### PR DESCRIPTION
**Pull request by Rikkola**
https://github.com/droolsjbpm/guvnor/pull/285
https://github.com/droolsjbpm/kie-wb-common/pull/302
https://github.com/droolsjbpm/drools-wb/pull/143
https://github.com/droolsjbpm/jbpm-console-ng/pull/364
https://github.com/droolsjbpm/optaplanner-wb/pull/46
https://github.com/droolsjbpm/kie-wb-distributions/pull/228

### CODE REVIEW

**Comment by Rikkola** [comment]
I keep forgetting optaplanner-wb.

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
master: 6acd1fbbcbb9b2baae532cf25cc4f449bd6a7476

**Pull request closed without merging**
