### PR TITLE
UF-295 - Upgrading lucene to 5.3.1

### PR DESCRIPTION
**Pull request by mrietveld**
See also: 

- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/optaplanner-wb/pull/56
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261

### CODE REVIEW

**Comment by mrietveld** [comment]
jenkins, please retest.

**Comment by manstis** [comment]
+1 to merge (when @porcelli has commented on @mrietveld's question in https://github.com/uberfire/uberfire-extensions/pull/258)

**Comment by mrietveld** [comment]
jenkins please retest

**Comment by mrietveld** [comment]
yes, jenkins, one more time: pretty please retest?

**Comment by psiroky** [comment]
@mrietveld you are getting close, optaplanner-wb is the one to blame this time :)

Welcome to the madness of upgrading (major version of) deps :)

**Comment by mrietveld** [comment]
@psiroky Thanks, Petr. :) I have at least 2 other PR's that are waiting for this one, as well.. :/

**Comment by mrietveld** [comment]
The build succeeds, but "fails" because it can not find the test results for the smoke tests.

**Comment by psiroky** [comment]
Test results were found, but screenshots directory was not. Never the less, there are three failing tests which are _not_ related to this PR. They have been failing for some time now and we are trying to figure out what is going on...

**Comment by mrietveld** [comment]
Thanks, @psiroky.

**Pull request merged**
