### PR TITLE
general deployment configuration after GWT upgrade

### PR DESCRIPTION
**Pull request by porcelli**

### CODE REVIEW

**Comment by porcelli** [comment]
@mswiderski @psiroky do you mind review this as well?
I've tested the artifacts on EAP and WildFly 8.1 and all seems to be working as expected... so would be good if you could test on other containers.

**Comment by mswiderski** [comment]
I'll take a look and try it out on WLS and WAS later today hopefully.

Anyway, it that works for EAP and Wildfly I guess it's fine to be merged and then we will fix the WLS and WAS if needed. wdyt?

**Comment by manstis** [comment]
Why do the -distribution-wars for Wildfly not have a "productized" profile build including the different JSPs etc? (see the -distribution-wars-cdi1.0 assemblies if you're not sure what I mean).

Also, kie-drools-wb-distribution failed to compile (since it needs to be changed to have dependencies on the -cdi1.0 WARs for non-Wildfly containers). I fixed this locally and confirmed (it also needs a change to droolsjbpm-build-bootstrap). 

I've pushed the changes there and merged this PR (with a change to kie-drools-wb-distributions) however we need the wildfly "productized" profile addressed (IDK if you do some other magic for this container, or whether the missing parts need to be added).

**Comment by manstis** [comment]
**droolsjbpm-build-bootstrap**
http://github.com/droolsjbpm/droolsjbpm-build-bootstrap/commit/6ae9f1547

**kie-wb-distributions**
http://github.com/droolsjbpm/kie-wb-distributions/compare/56bb8fe...dbaad05

**Comment by mswiderski** [comment]
@manstis isn't that wildfly not supported product container? and thus no need to have productized stuff for it...

**Comment by manstis** [comment]
That would make perfect sense!

**Comment by manstis** [comment]
Checking deployment of WARs (EAP's first).

Whilst the webapp deployed when logging in the browser remained empty "Loading..." and the Chrome Console shows:-
```
GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/css/ProcessList.css 
kie-wb.html:16 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/css/Forms.css 
kie-wb.html:17 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/css/HumanTasks.css 
kie-wb.html:19 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/css/timebox.css 
kie-wb.html:36 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/org.kie.workbench.KIEWebapp.nocache.js 
kie-wb.html:43 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/ace/mode-javascript.js 
kie-wb.html:40 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/ace/theme-chrome.js 
kie-wb.html:41 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/ace/mode-html.js 
kie-wb.html:42 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/ace/mode-css.js 
kie-wb.html:38 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/ace/ace.js 
kie-wb.html:45 GET http://localhost:8080/kie-wb-6.3.0-SNAPSHOT-eap6_4/org.kie.workbench.KIEWebapp/ace/ext-language_tools.js 
```
The WAR I generated here does in deed lack a org.kie.workbench.KIEWebapp folder.. so something's being filtered out incorrectly.... looking into.

**Comment by manstis** [comment]
kie-drools-wb WARs appear unaffected.

**Comment by manstis** [comment]
Fixed.

http://github.com/droolsjbpm/kie-wb-distributions/commit/d2bfa2abd

**Pull request closed without merging**
