### PR TITLE
[6.5.x][RHBRMS-2709] use Hibernate 4 in WFLY10/EAP7 WARs

### PR DESCRIPTION
**Pull request by psiroky**
Upgrading just core Hibernate libraries which seems safe.
Hibernate Validator was not updated as it causes compatibility
issues with javax.validation, Weld and RestEasy.

### CODE REVIEW

**Comment by psiroky** [comment]
@manstis, @mswiderski could you please quickly review this?

**Comment by mswiderski** [comment]
looks ok to me, if I got it right, it's to align it with all other assemblies that do use hibernate 4, correct?

**Comment by psiroky** [comment]
@mswiderski basically yes. As per GSS we don't want to support multiple Hibernate versions for 6.x.

**Comment by psiroky** [comment]
@mswiderski is there anything else required, or can we merge this?

**Comment by mswiderski** [comment]
+1 to merge, please go ahead and merge

**Pull request merged**
