### PR TITLE
[6.5.x] RHBPMS-4571: It is not possible to deploy business central on IBM WebSphere

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/RHBPMS-4571

### CODE REVIEW

**Comment by karreiro** [comment]
@porcelli Could you please take a look?

**Comment by psiroky** [comment]
It would be really great if the commit message explained how does this fix the issue. Why is that config not supported on WAS? Can we do something with that, or are there any alternative solutions? These kind of commit messages really do make life easier when looking at the changes few months from now...

**Comment by baldimir** [comment]
Doesn't this reintroduce security issue from https://issues.jboss.org/browse/RHBPMS-4383 ?

**Comment by triceo** [comment]
@baldimir It does. The issue will never be fixed on WAS.

**Comment by karreiro** [comment]
Thanks for the comment @psiroky. When the "<http-only>" is enabled, the WebSphere does not allow changes on the session cookie, which causes an error on the business central start up. This issue can be avoided by removing the cookie from "Security > Global security > Programmatic session cookie configuration" on the WAS. However, I talked to @porcelli and we decided that would be reasonable to remove the property from WARs generated to WebSphere.

**Pull request merged**
