### PR TITLE
Admin Page perspective selenium test

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by psiroky** [comment]
Looks good. @jhrcek could you please quickly check this?

**Comment by psiroky** [comment]
I mean, we should merge the "Admin" and "Administration" perspectives. But till that happens, checking the other perspective should be useful as well.

**Comment by jhrcek** [comment]
+1 to merge

**Pull request merged**
