### PR TITLE
Fix Selenium integration test following i18n changes

### PR DESCRIPTION
**Pull request by manstis**
See https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-distributions/1402/testReport/

Looks like a Selenium test started failing following some i18n changes.

### CODE REVIEW

**Comment by manstis** [comment]
"Yes" these tests remain as brittle as erm [brittle](https://en.wikipedia.org/wiki/Brittle_(food))

**Comment by manstis** [comment]
@adrielparedes @porcelli Please see https://github.com/uberfire/uberfire/pull/504#issuecomment-248234742 The remaining failing tests are, I suspect, caused by the change in Uberfire.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
+1

**Pull request merged**
