### PR TITLE
Fix style for selected nav bar item on product

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
@manstis you're faster than me ;). Still running the build to test.

**Comment by manstis** [comment]
@csadilek heh, I didn't compile to test.. it looked like some CSS changes for a gradient fill on the navbar so I thought there couldn't be much wrong.. ;)

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
Thanks.

master: 0ec54f9a24f3fdac1aaae11417bfddefc3441af6

**Pull request closed without merging**
