### PR TITLE
JBPM-4903 - Adjust ContextualSearch perspective setup

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
depends on https://github.com/droolsjbpm/kie-wb-common/pull/219

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Test failures look unrelated. I will run locally though to confirm.

**Comment by psiroky** [comment]
The failures were related to mis-configuration on Jenkins. Should be fixed now (I re-triggered the build as well).

**Comment by csadilek** [comment]
6.4.x: 859e8fa239fad3e8d39aaceacb099b16b7261039

@cristianonicolai are all of those needed on master as well, I assume?

**Comment by cristianonicolai** [comment]
@csadilek yep, just landed https://github.com/droolsjbpm/kie-wb-distributions/pull/183 :)

**Pull request closed without merging**
