### PR TITLE
[6.5.x] RHBRMS-2598: Asset search is broken

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/RHBRMS-2598

Cherry-pick of https://github.com/droolsjbpm/kie-wb-common/pull/471 (of sorts) for 6.5.x (Code changes are similar but had to be applied manually to 6.5.x since it has a different code structure to master).

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/uberfire/uberfire-extensions/pull/303
- https://github.com/droolsjbpm/kie-wb-distributions/pull/358

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
6.5.x is currently broken due to https://github.com/uberfire/uberfire-extensions/pull/301#issuecomment-248253697

**Comment by csadilek** [comment]
+1

**Pull request merged**
