### PR TITLE
Drop IE9 and IE10 GWT permutations

### PR DESCRIPTION
**Pull request by psiroky**
* we only need to support IE 10+

### CODE REVIEW

**Comment by manstis** [comment]
I believe IE10 has also been dropped (at least in product).

@krisv @etirelli Can either of you please advise whether we can drop IE10 in community too?

**Comment by psiroky** [comment]
Yes, I believe we could actually do that. In case we need to support IE 10 again in future, we could always add it back.

**Comment by etirelli** [comment]
@manstis @psiroky for community we can drop IE10, but for product unfortunately I don't think a decision was made yet. I am trying to confirm this and will let you know.

**Comment by manstis** [comment]
OK,  that's not the message Kris was giving me earlier this week!

**Comment by etirelli** [comment]
@manstis @psiroky Prakash just confirmed we can drop it for now. So go for it. :)

**Comment by psiroky** [comment]
I've updated the PR accordingly.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks!

master: 402487a4fb649882720c82e97114302b20b764c5
6.3.x: 0fb0d806e2ae7e6700d907c2c33d4e6bb4992c55

**Pull request closed without merging**
