### PR TITLE
Upgrade to GWT 2.8.0-rc1

### PR DESCRIPTION
**Pull request by csadilek**

### CODE REVIEW

**Comment by csadilek** [comment]
Needs:

droolsjbpm/droolsjbpm-build-bootstrap#250
errai/errai#184
uberfire/uberfire#461
https://github.com/droolsjbpm/drools-wb/pull/263

**Comment by manstis** [comment]
+1 to merge (but ```ecj``` comment probably needs investigating as suggested by @psiroky)

**Comment by csadilek** [comment]
ejc comment removed

**Comment by manstis** [comment]
+1 to merge (when green).

**Pull request merged**
