### PR TITLE
Fix build: asset-mgmt-project no longer exists

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by mswiderski** [comment]
+1

**Comment by psiroky** [comment]
@mswiderski let's wait for the build to finish as I did not run it locally.

**Comment by mswiderski** [comment]
@psiroky +1 is implicitly bound to build success :)

**Comment by psiroky** [comment]
@mswiderski I wasn't actually 100% sure about that :)

**Comment by psiroky** [comment]
Not sure if the test fail is related to these changes, will try to investigate.

**Comment by psiroky** [comment]
Since it will take me some time to investigate this; and without these changes the build fails, I would vote for merging it asap. In case I found what is wrong with the tests, I will submit new PR.

**Comment by mswiderski** [comment]
+1

I don't see anyway how this test failure could be related to this change...

**Comment by psiroky** [comment]
I see that one of the earlier PR builds was actually successful (before I changed the commit message and which caused re-triggering the build), so the test is likely just unstable. Will merge this.

**Pull request merged**
