### PR TITLE
PLANNER-686: Workbench: Move Planner-specific code from kie-wb-common to optaplanner-wb

### PR DESCRIPTION
**Pull request by mcimbora**
Move PermissionTreeSetup & WorkbenchTreeProvider classes here from kie-wb-common, as they reference downstream content (Planner).

### CODE REVIEW

**Comment by mcimbora** [comment]
Part of:
droolsjbpm/droolsjbpm-build-bootstrap#309
droolsjbpm/kie-wb-common#540
#118
droolsjbpm/kie-wb-distributions#396

**Comment by manstis** [comment]
@wmedvede @ederign IIRC you two probably know the most about "Docks".. could you please review?

**Comment by mcimbora** [comment]
Jenkins retest this.

**Comment by wmedvede** [comment]
Hello @manstis @dgutierr ,
please see my comments in https://github.com/droolsjbpm/kie-wb-common/pull/540 with reference to moving all the securrity settings from kie-wb-commons to kie-wb-distributions/kie-wb and kie-wb-distributions/kie-drools-wb

**Comment by manstis** [comment]
@dgutierr could you please assist @wmedvede

**Comment by mcimbora** [comment]
Closing as this blocks multiple smaller issues that will be addressed separately. Will reopen once a better solution is found.

**Pull request closed without merging**
