### PR TITLE
fixed missing / in history url pattern that might cause issues with m…

### PR DESCRIPTION
**Pull request by mswiderski**
…atching of urls

on EAP it causes following message to be printed upon startup:
```
14:21:37,281 INFO  [org.apache.catalina.core] (ServerService Thread Pool -- 74) JBWEB001107: Suspicious url pattern: /kie-wb in context /rest/history* - see section SRV.11.2 of the Servlet specification
```

### CODE REVIEW

**Comment by mswiderski** [comment]
anyone comments on this or shall we merge it? I believe it makes sense to have that in 6.3.0

**Comment by manstis** [comment]
@mswiderski No comments from me.. other than it looks innocuous to me! 

@mrietveld You're possibly closer to/more knowledgeable about this... thoughts?

**Comment by mrietveld** [comment]
+1 -- I was going to push this later today. :)

**Comment by mswiderski** [comment]
ok, then I leave that to you @mrietveld 
thanks

**Comment by mswiderski** [comment]
this must be merged and cherry picked to 6.3.x as kie-wb fails to deploy on Weblogic

@mrietveld will you do it or shall I merge it in and send commit ids to @mbiarnes?

**Comment by mrietveld** [comment]
@mswiderski apologies -- I will be merge this to master and cherry-pick this tonight.

**Comment by mrietveld** [comment]
Merged @ https://github.com/droolsjbpm/kie-wb-distributions/commit/0fbb70f53c810ee0387f0c5225920696b8e5da78

**Pull request closed without merging**
