### PR TITLE
Refactor selenium smokes (add Graphene for easier extensibility)

### PR DESCRIPTION
**Pull request by jhrcek**
This depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/192

### CODE REVIEW

**Comment by jhrcek** [comment]
Jenkins retest this, because I forgot to give the same name to the branch in related PR

**Comment by jhrcek** [comment]
@psiroky I made some small changes for IE and verified the tests are working both with FF and IE on windows. Should be ready for review / merge.

**Comment by psiroky** [comment]
LGTM. @csadilek or @cristianonicolai could you please take a look as well as this is GUI-related?

**Comment by csadilek** [comment]
+1

**Pull request merged**
