### PR TITLE
Bug 1304447 - [GSS](6.2.z) Not able to select specific branch from repository

### PR DESCRIPTION
**Pull request by Rikkola**
https://github.com/droolsjbpm/guvnor/pull/264
https://github.com/droolsjbpm/kie-wb-common/pull/278
https://github.com/droolsjbpm/drools-wb/pull/132
https://github.com/droolsjbpm/jbpm-console-ng/pull/341
https://github.com/droolsjbpm/jbpm-designer/pull/161
https://github.com/droolsjbpm/jbpm-form-modeler/pull/38
https://github.com/droolsjbpm/kie-wb-distributions/pull/209

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
CreateRepositoryCliCommand needed an update too.

**Comment by manstis** [comment]
+1 to merge (good catch Jenkins!)

**Comment by Rikkola** [comment]
kie-config-cli still broken. Fixing.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
Jenkins picking up what I missed. Optaplanner-wb needs update, even after spending most of this year on optaplanner I still only updated the drools and jppm webapps.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
Selenium tests broken. Fixing those.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
@Rikkola I merged the 6.3.x series of these PRs, but holding off here because I can't tell if the test failure could be related to a relevant change. Can you verify and let me know, please?

**Comment by csadilek** [comment]
@Rikkola @manstis After this is merged on master, I guess we need it for 6.4.x as well?

**Comment by manstis** [comment]
@csadilek Yes.

**Comment by Rikkola** [comment]
Working on the 6.4.x PRs.
I managed to get the tests to pass yesterday (with no changes, I just reran the tests), but before that I had the same test failing.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
I'd be ok with merging this (once conflicts are resolved) despite this test failure and investigate separately. This PR is too involved to keep it pending ;).

**Comment by csadilek** [comment]
master: adc5567e36fb4c967724cdf68aeed6ed4241aa6a

**Pull request closed without merging**
