### PR TITLE
BZ-1290025 - Updated deploy image

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
@cristianonicolai Do the other locales need changing too?

**Comment by cristianonicolai** [comment]
@manstis no, sorry, I forgot to mention that this is only to fix another typo.

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
master - https://github.com/droolsjbpm/kie-wb-distributions/commit/815ce748c00e9741271f36488f0d1890838f287c

**Pull request closed without merging**
