### PR TITLE
[DROOLS-797] use different classifier for productized builds

### PR DESCRIPTION
**Pull request by psiroky**
* this way we can have both variants in same repo as Maven
   itself can differentiate between them using the classifier

@ryanzhang can you please take a look and let me know if this change somehow make you life harder? Basically all you need to change on your side are the artifact coordinates -- e.g. adding the new classifier.

### CODE REVIEW

**Comment by psiroky** [comment]
@manstis @porcelli please review, but don't merge yet. Let's wait for input from @ryanzhang.

**Comment by manstis** [comment]
@psiroky Looks good to me.

**Comment by porcelli** [comment]
@psiroky looks good to me too.

**Comment by ryanzhang** [comment]
Ok,  it looks fine to me. 
(After conversation with Petr),  we think we might also want to do the same to dashbuilder.war which is producted in jbpm-dashboard.git.

**Comment by psiroky** [comment]
Thanks Ryan. I will merge this and then look into the dashbuilder changes.

**Comment by psiroky** [comment]
Merged into master as https://github.com/droolsjbpm/kie-wb-distributions/commit/fb10fee81ca58c31d1a1db76d704e7adeef56503

**Pull request closed without merging**
