### PR TITLE
JBPM-5530 - Update process-runtime GWT module name

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/droolsjbpm/jbpm-console-ng/pull/602

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
The Selenium tests are failing since Project Explorer in the Authoring Perspective appears to be "collapsed" into a "Dock" and hence the CSS selector used in the tests cannot locate the Project Explorer. IDK if this relates to changes made recently by @paulovmr ?

**Comment by cristianonicolai** [comment]
Jenkins please retest this.

**Comment by cristianonicolai** [comment]
Jenkins please retest this.

**Comment by cristianonicolai** [comment]
@manstis ProjectAuthoringIntegrationTest and ProjectAuthoringIntegrationTest seem to be failing randomly with multiple PRs.

**Comment by manstis** [comment]
@cristianonicolai Yes indeed. It's possibly caused by @paulovmr change to collapse the Project Explorer on the Authoring Perspective. I have pinged @paulovmr on another PR asking him to check things.

**Pull request merged**
