### PR TITLE
BZ1278888: [GSS](6.1.z) 'create-repo' command from kie-config-tool does not work properly in BPM Suite

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1278888

### CODE REVIEW

**Comment by manstis** [comment]
@wmedvede Hi Walter.... could you please review this (6.2.x)?

**Comment by manstis** [comment]
This builds fine locally, with a locally built droolsjbpm-build-bootstrap@6.2.x. I'm using Maven 3.3.3 locally. @psiroky Is there something "special" about the CI jobs that would lead to "transient dependencies" errors on Jenkins but not local?

**Comment by psiroky** [comment]
It seems the build itself went fine, but Jenkins failed when collecting the test results. For master and 6.3.x there are some tests in this repo so that works fine. However, for 6.2.x no tests were executed (as there are none it seems). I did some job configuration magic and re-triggered the build, so let's see if that helps.

**Comment by manstis** [comment]
@psiroky thanks.. I saw:
```
[ERROR] Found 2 illegal transitive type dependencies in artifact 'org.kie:kie-wb-webapp:war:6.2.1-SNAPSHOT':
11:55:23 1.) org.kie.workbench.common.screens.social.hp.config.SocialConfigurationService
11:55:23 2.) org.uberfire.backend.vfs.VFSService
``` 
in the build logs too, so assumed it was a "transient dependency" issue problem.

**Comment by psiroky** [comment]
Yeah, for 6.2.x we did not yet enforce the direct dependencies. Only warnings are printed, but the build does not fail.

**Comment by psiroky** [comment]
The build was successful, yay!

**Comment by csadilek** [comment]
@wmedvede can you review?

**Comment by wmedvede** [comment]
yes, the repositories created by the client config tool should me marked as Unmanaged.

+1 to merge.

**Comment by csadilek** [comment]
Thanks.

6.2.x: 75463a9ede396ba6bfa70b015b71a0628b137293

**Pull request closed without merging**
