### PR TITLE
[DROOLS-729] Android Support documentation

### PR DESCRIPTION
**Pull request by kedzie**
This is documentation for DROOLS-729 Android integration.

Pull requests:
* droolsjbpm/droolsjbpm-integration#118
* droolsjbpm/drools#416.

### CODE REVIEW

**Comment by kedzie** [comment]
@mariofusco have a look at this plz.. This sufficient?

**Comment by kedzie** [comment]
Rebased.  have a look at this @psiroky since we are merging the other PRs.

**Comment by psiroky** [comment]
I'll review and merge this in the upcoming days.

**Comment by psiroky** [comment]
Merged into master as https://github.com/droolsjbpm/kie-wb-distributions/commit/f86de3461fe74404a8f943b3e39224ccd9de5d6c. Thanks @kedzie!

**Pull request closed without merging**
