### PR TITLE
BZ-1275796 - Move menu items into new utility menu bar

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by manstis** [comment]
@cristianonicolai Unrelated, do you know when the "Search..." menu item is to be re-introduced? It was removed by @porcelli with the BS2 to BS3 migration.

**Comment by csadilek** [comment]
Thanks!

master: 6adc3829813dfdb0761e1c96973b712d7594d83d

**Comment by cristianonicolai** [comment]
@manstis I'm not sure, I don't recall seen that in any proposed design using PatternFly.

**Pull request closed without merging**
