### PR TITLE
[master] BZ1321821 - Add kiemgmt role to WLS web*.xml

### PR DESCRIPTION
**Pull request by zkrejcov**

### CODE REVIEW

**Comment by manstis** [comment]
@zkrejcov Thanks for doing the fix (as well as reporting)

+1 to merge.

**Comment by zkrejcov** [comment]
The test fails are in selenium tests, as far as i can tell, they timed-out waiting for the kie workbench to load. Unless these tests run on WLS, this should be unrelated.

**Comment by psiroky** [comment]
The tests are running on Tomcat, so the fails are not related. (although we need to figure out why the tests are failing...)

**Comment by csadilek** [comment]
master: 294fc5c07c3a6b0e4b46d03621e7c41d45918125

**Pull request closed without merging**
