### PR TITLE
BZ1320502: AdministrationPerspective not loading for administrative u…

### PR DESCRIPTION
**Pull request by jesuino**
BZ1320502: AdministrationPerspective not loading for administrative user whose roles is not defined as "admin"

### CODE REVIEW

**Comment by manstis** [comment]
@jesuino -1 to this I am afraid.

Whilst what you've done is part of the solution it simply removes all restrictions to access of the Administration Perspective. What is also needed is to protect access to this Perspective by using ```KieACL``` on the Menus/Home Page sections etc so that access can be restricted by configuration.

I've cc'ed @paulovmr who has been assigned the BZ for his awareness that you are also looking into a fix.. @paulovmr and I spoke briefly on IRC yesterday about what was required. Please liaise with him.

**Comment by jesuino** [comment]
@manstis Yesterday we were in a hurry with this issue, so I thought to speed up by providing a PR just in case this was that simply. I was skeptical this could be the solution as well.
I will talk to @paulovmr  - thanks!

**Comment by paulovmr** [comment]
@manstis Hi, I took a look in this issue and it seems that all menu access to this feature are already protected by KieACL ([kie-wb](https://github.com/droolsjbpm/kie-wb-distributions/blob/master/kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java#L264) and [kie-drools-eb](https://github.com/droolsjbpm/kie-wb-distributions/blob/master/kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java#L263)). Also, the workbench-policy.properties files already cover this feature in their roles.

So I tested @jesuino 's solution and it worked locally for me. Is there anything else we are missing?

**Comment by manstis** [comment]
Great stuff; if use of KIE ACL is already implemented then there is little else to do than remove the Role annotations. Thanks to you both.

**Comment by manstis** [comment]
+1 to merge.

**Comment by psiroky** [comment]
Sorry to intrude, I was trying the new Github feature: https://github.com/blog/2141-squash-your-commits. This is exactly what I was waiting for for the past few months! We can now merge with rebase directly from Github UI!

**Comment by manstis** [comment]
@psiroky Does the squash rebase rather than merge to keep linear history? It'd be lovely to be able to commit PRs via github's UI rather than CLI.

**Comment by psiroky** [comment]
@manstis yes it does rebase. I merged this PR via the UI and there is no merge commit associated with it when looking at https://github.com/droolsjbpm/kie-wb-distributions/commits/master

**Pull request merged**
