### PR TITLE
GUVNOR-2521: Consolidate server-side bootstrap logic in various workbench implementations

### PR DESCRIPTION
**Pull request by paulovmr**
Depends on:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/214
https://github.com/droolsjbpm/kie-wb-common/pull/376
https://github.com/droolsjbpm/drools-wb/pull/189

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (with others).

Failing test leading to Jenkins failure is unrelated to this PR and fails on master too. 

@mrietveld has undertaken to investigate the failing test..

**Comment by manstis** [comment]
@paulovmr @dgutierr There's going to be a conflict between your PRs.. who wants to "go first" ;)

Paulo's PRs are ready for merge; I think David's are still in progress... you two decide who wants to fix the resulting conflicts on whatever PRs go "second"... Paulo's may be easier to fix than Davids.. IDK.

**Comment by paulovmr** [comment]
@manstis Thanks for all reviews!

@manstis @dgutierr Since mine are easier to fix, I don't mind "going second". :)

**Comment by csadilek** [comment]
@paulovmr great work! Love it. 

@manstis @dgutierr I don't think we should start serializing PRs as we might soon end up with a long backlog. If it's ready, I think we should merge. I know conflicts are a pain but it goes both ways.

**Comment by manstis** [comment]
@csadilek OK.. fair enough. I don't mind.. I was just letting @dgutierr and @paulovmr agree the pain. We're waiting on a comment for @paulovmr 's LiveSpark PR atm.. but I suspect it won't be anything to worry about.

**Pull request merged**
