### PR TITLE
GUVNOR-2443: New Screen: Import example Project(s) from git Repository

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2443

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/156
https://github.com/droolsjbpm/kie-wb-common/pull/316
https://github.com/droolsjbpm/drools-wb/pull/147
https://github.com/droolsjbpm/kie-wb-distributions/pull/232

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
@manstis does optaplanner-wb need this as well?

**Comment by csadilek** [comment]
master: 17a0ef60c3ec23bee443e65dc13b726b8480b804

**Comment by manstis** [comment]
@csadilek "Does ```optaplanner-wb``` need this as well"...My opinion is that the *only* distribution we have are ```kie-wb``` and ```kie-drools-wb``` every other webapp (e.g. ```drools-wb```, ```jppm-console-ng```, ```jbpm-designer-standalone``` etc) is gravy and inclusion of these screens a nicety.. that to be honest those maintaining the other "developer niceties" can import *if they wish*. All the foregoing webapps still import examples, but not via the new screen.

**Pull request closed without merging**
