### PR TITLE
[6.4.x] PLANNER-523 : Workbench: add optaplanner solver editor functionality in kie distributions, but masked out by role plannermgmt

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit 39f88e9e2bb05b2e07f150d93c6112daf4ecd3e0)

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by ge0ffrey** [comment]
+1

**Comment by csadilek** [comment]
Test failures unrelated. I put it on my todo list to see why this happens after my PTO, unless someone gets to it first ;).

6.4.x: 7dd445616f3fe529c70f63322fb507de1f22204b

**Comment by psiroky** [comment]
It seems that the tests are failing only on single CI machine. I've been looking at that briefly, but could not find anything out of the ordinary there. I've disabled the machine for now, to see if we get the failures on other ones or not.

**Pull request closed without merging**
