### PR TITLE
Fix test failing for productization

### PR DESCRIPTION
**Pull request by mrietveld**
See https://github.com/jboss-integration/kie-wb-distributions/pull/7

### CODE REVIEW

**Comment by mrietveld** [comment]
The repositories GET functionality is also tested at other parts in this test suite.

**Comment by manstis** [comment]
@mrietveld Before I OK the removal of a test, could you be so kind as to point out exactly where repositories GET functionality is still tested? ;)

**Comment by mrietveld** [comment]
Added some code to do more tests here: 

https://github.com/mrietveld/kie-wb-distributions/blob/da0329986b96613f206afc12fe4223c13e97fe00/kie-wb-smoke-tests/src/test/java/org/kie/smoke/wb/rest/GuvnorRestSmokeIntegrationTest.java#L230

Existing tests of the repositories GET functionality:   

https://github.com/mrietveld/kie-wb-distributions/blob/da0329986b96613f206afc12fe4223c13e97fe00/kie-wb-smoke-tests/src/test/java/org/kie/smoke/wb/rest/GuvnorRestSmokeIntegrationTest.java#L230
https://github.com/mrietveld/kie-wb-distributions/blob/da0329986b96613f206afc12fe4223c13e97fe00/kie-wb-smoke-tests/src/test/java/org/kie/smoke/wb/rest/GuvnorRestSmokeIntegrationTest.java#L256
https://github.com/mrietveld/kie-wb-distributions/blob/da0329986b96613f206afc12fe4223c13e97fe00/kie-wb-smoke-tests/src/test/java/org/kie/smoke/wb/rest/GuvnorRestSmokeIntegrationTest.java#L280


I'm having a very allergic reaction to the fact that a PR that fixes a test (this one) is getting more significantly more attention than the PR that ignores it ( https://github.com/jboss-integration/kie-wb-distributions/pull/7 ). >:(

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks.

master: 5cadc24347bf40a005d33708e9aab92fc39229ef

**Pull request closed without merging**
