### PR TITLE
Remove kie-wb-smoke-tests module

### PR DESCRIPTION
**Pull request by livthomas**
After jBPM runtime has been removed from KIE Workbench ([JBPM-5071](https://issues.jboss.org/browse/JBPM-5071)) the remote runtime tests in this module are not needed anymore. Guvnor REST API tests has also been replaced by much larger test suite in `kie-wb-tests` module ([GUVNOR-2504](https://issues.jboss.org/browse/GUVNOR-2504)) That means `kie-wb-smoke-tests` module can be deleted.

### CODE REVIEW

**Comment by psiroky** [comment]
+1

**Comment by mrietveld** [comment]
+1

**Comment by manstis** [comment]
@livthomas @psiroky @mrietveld Does this PR have dependencies on any other PR(s)?

**Comment by mrietveld** [comment]
@manstis Not AFAIK. 

kie-remote-services also needs to be deleted, but not before we migrate the Query REST operations to kie-server.

**Pull request merged**
