### PR TITLE
Add EAP7 cargo config

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
The test failures are very likely not related, because those tests are failing without the changes as well. That being said, we definitely need to fix those before merging this.

**Comment by psiroky** [comment]
Thanks for looking at this @manstis!

**Comment by manstis** [comment]
@psiroky No problem.. all tests were green when I merged :-)

**Comment by psiroky** [comment]
@manstis yeah, I did trigger the build again to see how much random the fails are :) and it worked in this case.

**Pull request merged**
